version: 1
deployments:
  - name: scraper
    entrypoint: workflow.py:print_events
    work_pool:
      name: default
    pull:
      - prefect.deployments.steps.git_clone:
          repository: "https://github.com/Chaimaekit/Events_Project.git"
          branch: main
    directory: /root/flows 
    schedules:
      - cron: "*/2 * * * *"
        timezone: UTC
