version: 1
deployments:
  - name: scraper
    entrypoint: workflow.py:print_events
    work_pool:
      name: default
      work_pool_type: docker
      job_variables:
        image: chaimaaeljerrar/scraping-image:latest  # Your built image
    schedules:
      - cron: "*/2 * * * *"
        timezone: UTC
