version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - backend
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

networks:
  backend:
    driver: bridge

