on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
            nohup python main.py &  # run in background
            sleep 5  # give it time to start

      - name: Test endpoint
        run: curl http://127.0.0.1:8000/stream_events_ma


